name: build

on:
  push:
    branches: [ master ]
    tags: [ '*' ]

jobs:
  purge_workflow_runs:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: sudo apt-get install -y jq
      - env:
          GH_TOKEN: ${{ github.token }}
        name: Purge
        run: |
          gh api repos/tonybogdanov/worker-relay/actions/runs --paginate | \
          jq '.workflow_runs[] | .id' | \
          xargs -t -I{} sh -c "gh api -X DELETE /repos/tonybogdanov/worker-relay/actions/runs/{} || true"

  test:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install vendors
        run: npm install
      - name: Run tests
        run: npm run test
